### ISSUE TITLE
Question about downloading the raw fastq files

### ISSUE THREAD

**Issue by faridrashidi** [buenrostrolab/slide_dna_seq_analysis#2]
Dear slide-DNA-seq developers,

First of all thank you very much for developing this amazing technique. I'm trying to download the raw fastq files from SRA and map them using the scripts provided in this repo. Could you please help me with how I can dump the SRA so that the three files required to run https://github.com/buenrostrolab/slide_dna_seq_analysis/blob/41142f767075df4ae84d2142cf4c771317a5da2f/scripts/run/slidedna_alignment_template.sh#L23 this script get downloaded?

I've been trying `fastq-dump --split-files` but apparently this command only downloads the paired files.

Thank you.

**Comment by zchiang** [comment]
Hi Farid, thanks for you interest in our data!

SRA is not designed to handle DNA barcodes, which is why it is difficult to find the R3 file. However, the following way should work
1) go to http://www.ncbi.nlm.nih.gov/sra?term=PRJNA768453
2) click on the dataset you want
3) click on the Run ID at the bottom of the page e.g. SRR16221020
4) click on the "Data Access" tab
5) download from either AWS or GCP.

Let me know if you have any issues!

**Comment by faridrashidi** [comment]
Thank you Zach (@zchiang) for your quick response!! I've tried following your guidance and downloading SRR16220120 from AWS but when I run the following command, I get an access denied error. Is the data publicly available?

```
aws s3 ls s3://sra-pub-src-16/SRR16220120 --no-sign-request

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Comment by zchiang** [comment]
I actually have not tried this process myself, but I think you may have to request the data via https://www.ncbi.nlm.nih.gov/Traces/cloud-delivery/

I'm playing around with this myself and will update if I discover an easier way, sorry for the inconvenience!

**Comment by ruqianl** [comment]
Hi @zchiang ,

Sorry for replying in a closed issue. But my question is relevant to this original post.
So I downloaded the fastq files from SRA for the snRNAseq data and split the reads, but it only contains two files:

R1_fq:
```
@SRR16220118.1 1 length=4
CTGG
+SRR16220118.1 1 length=4
AAAA
@SRR16220118.2 2 length=4
AAAC
+SRR16220118.2 2 length=4
```


R2_fq:
```
@SRR16220118.1 1 length=60
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+SRR16220118.1 1 length=60
############################################################
@SRR16220118.2 2 length=60
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

It does not include a I1_fq file which I assume should encode the cell barcodes? Or is the cell barcodes contained in R2?

BTW, the first read only has 4 base pairs, could you confirm that is right?

Thanks for your help in advance.

Best regards,
Ruqian

**Comment by zchiang** [comment]
Hi [ruqianl](https://github.com/ruqianl),

Thanks for you interest in our data! There are a few issues at work here:

- SRA is incorrectly labeling the I1.fastq file as R1, which is why you only see 4 bp in that file
- the I1.fastq is only there for completeness and is not particularly informative, as we only sequenced one sample (10x uses 4 I1 barcodes per sample)
- both the cell barcode and the UMI are found in the real R1, which is 28 bp
 ([see here for more info](https://teichlab.github.io/scg_lib_structs/methods_html/10xChromium3.html))

<img width="1330" alt="Screen Shot 2022-03-24 at 1 44 19 PM" src="https://user-images.githubusercontent.com/9100334/159978214-6658a9d8-ef86-4fe7-89b6-704e092c9fbb.png">

To get the real R1 file, you can either follow the directions above to download it via AWS, or I uploaded it to a Dropbox [here](https://www.dropbox.com/sh/eschwvw7mcye229/AAAT48wWHhoXf8EOB-aqWt2Ua?dl=0). Once you get it, we typically just use 10x's CellRanger software to do the initial processing of these files

The R2 file looks correct to me. Let me know if you run into any other issues!

**Comment by ruqianl** [comment]
Thanks very much for the clarification and the useful links!

I explored the cloud transferring method a bit. Unfortunately, we don't have a billing account from google cloud or AWS yet, and it looks like it costs a bit more from the region I'm in (Australia).  Thanks for the dropbox link! 

Ruqian

**Comment by shashwatsahay** [comment]
Hi @zchiang 

I am having the same issue

Is there any update on finding a way to get these files easily without requiring a paid cloud account. Maybe if it would be possible to use a zenodo repo to upload the raw files.

**Comment by zchiang** [comment]
Hi @shashwatsahay, sorry for not seeing this earlier! (I don't get notifications on closed issues.)

If you (or anyone in the future reading this) are interested in downloading the raw FASTQs without AWS, I have uploaded them here: https://drive.google.com/drive/folders/18ArSJdunOkSV9mffsRwNBae86GU6Xr62?usp=sharing
