### ISSUE TITLE
Sparse counts data

### ISSUE THREAD

**Issue by HeidiOttesen** [buenrostrolab/slide_dna_seq_analysis#3]
Hi guys.

I am working on my master thesis studying slideseq data. So thank you for all your work on this and for this repository!
I've got a question about the published "*.sparse_counts_1Mb.txt" - DNA files. 
What do they actually represent here?
- Has the data been normalized in any way?
- Have you already applied knn-analysis or other methods?
- Are the counts raw data? What is your input fragment files?
- How long are the fragments -> PCR-templates -> sequencing reads? 
- Could there be multiple (smaller) fragments from the same cell hitting the same bin? -> false higher bin counts? (especially on the high count values from 25 to 200)

Tried getting an idea from the [preprocess script](https://github.com/buenrostrolab/slide_dna_seq_analysis/blob/main/scripts/preprocess/get_sparse_counts.py) but wanted to check with you.

Hope to hear from you

Best wishes
Heidi

**Comment by zchiang** [comment]
Hi Heidi,

Thanks for your interest in our data! To answer your questions:

- The data in the sparse counts matrix have not been normalized yet
- No k-nearest neighbor aggregation has been performed yet
- Yes, raw counts. We create the sparse matrix using scripts/preprocess/get_sparse_counts.py which takes a list of genomics reads, a list of bead barcodes, and a list of bins and fills out the matrix accordingly. The list of genomic reads is the final output of the alignment pipeline (scripts/run/slidedna_alignment_template.sh)
- The genomic fragments are typically a few hundred bp long. The read length varies by sample, but I believe most are 57 bp paired-end reads (excluding indices).
- When we create the sparse counts matrix, we sort the genomic reads into bins based on the leftmost genomic coordinate of the paired end read. In principle, a genomic fragment could overlap two bins, but in practice this is exceedingly rare given the length of the genomic fragment (on the order of 100 bp) relative to the length of our bins (1 Mb)

Hope this helps, please let me know if anything is unclear or you have further questions!
Zack

**Comment by HeidiOttesen** [comment]
Hi again.
Thank you for addressing all my queries, very helpful.
Just to clarify the last question - I was thinking more the opposite - not that one fragment hits two different bins but that several different fragments (short ~100bp) could hit the same bin (1Mb) - leading to a higher count. But if I understand your reply correctly, only the left-most unique fragment qualifies as a count then?

Do you have any theories to the high outliers? I found counts up to 506 in the mouse liver met2 dataset. CNAs/misalignments/bias/technical errors?

Thank you again! 
Kind regards
Heidi

**Comment by zchiang** [comment]
I believe you are understanding my reply correctly, but will write out a quick explanation just to make sure:

- We perform paired-end sequencing, so every genomic fragment is sequenced from both ends
- When we remove PCR duplicates, we keep only unique fragments based on genomic coordinates
- Each unique read counts once towards the counts matrix (based on the left-most position)

In general, we think the higher/lower bin counts can be explained by a combination of real biological signal (whole chromosome duplications/deletions in this case) and the known sequence biases of our assay (see Supp Fig. 5). There are two outlier bins in the mouse liver met data -- chrM, which is obviously due to there being many more copies of the mitochondrial genome, and chr2 9.8-9.9 Mb. We have not followed up to see why there are so many reads aligning to this chr2 bin, but we exclude it from downstream analysis in the bin selection step before PCA.

**Comment by HeidiOttesen** [comment]
This is great. Thank you so much!
